language: cpp
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages:
    - gfortran
    - octave
    
matrix:
  include:
  - os: linux
  # - windows  # needs gfortran, straightforward to add but already on appveyor
  #- os: osx  # save time
  #  before_install:
  #  - brew install gcc > /dev/null
  #  - brew install octave > /dev/null

install: 
- cd bin
- cmake ..
- cmake --build .

script:  ctest --output-on-failure
