language: sh
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

os:
- osx
- linux
- windows

addons:
  apt:
    packages:
    - octave

before_script: cd $TRAVIS_BUILD_DIR/bin

script: cmake ..
