language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - gfortran-6
        - octave
  - os: linux
    python: 3.5
    install: pip install -e .[tests]
    script:
    - pytest -v
  - os: linux
    name: Integration install
    python: 3.7
    install:
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR/tests
  - os: linux
    language: python
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    - pytest -v
    after_success:
    - pytest --cov
    - coveralls
# -os: windows  # needs gfortran, straightforward to add but already on appveyor
#  - os: osx  # just saving CI time
#    env: FC=gfortran
#    before_install:
#    - brew install gcc > /dev/null
#    - brew install octave > /dev/null

install:
- cd build
- cmake ..
- cmake --build .

script:  ctest --output-on-failure
