language: cpp
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran-6

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - octave

cache:
  directories:
  - $HOME/Library/Caches/Homebrew

before_cache:
- brew cleanup

matrix:
  include:
  - os: linux
  # - windows  # needs gfortran, straightforward to add but already on appveyor
  - os: osx
    env: FC=gfortran
    before_install:
    - brew install gcc > /dev/null
    - brew install octave > /dev/null

install:
- cd build
- cmake ..
- cmake --build .

script:  ctest --output-on-failure
