language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python: 3.7

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - gfortran-6
        - octave
  - os: linux
    python: 3.6
    install: pip install -e .[tests]
    script:
    - pytest -r a -v
  - os: linux
    name: Integration install
    install:
    - python setup.py install
    - pip install $(basename $TRAVIS_REPO_SLUG)[tests]
    script:
    - cd $HOME
    - python -m pytest $TRAVIS_BUILD_DIR
  - os: linux
    language: python
    install: pip install -e .[tests,lint]
    script:
    - flake8
    - mypy .
    - pytest -r a -v
    after_success:
    - pytest --cov
    - coveralls

install:
- cd $TRAVIS_BUILD_DIR/build
- cmake ..
- cmake --build . --parallel

script:  ctest --parallel --output-on-failure
