name: ci_python
env:
  cmake_version: '3.17.2'
  ninja_version: '1.10.0'
  CI: true
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**.py"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: prereq install
      run: |
        sudo apt update -yq > /dev/null
        sudo apt-get install -yq --no-install-suggests --no-install-recommends octave
    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest

    - name: Install CMake
      run: |
        python cmake_setup.py ${cmake_version} --prefix ${HOME}/.local
        echo "::add-path::${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin"

    - name: Install Ninja
      run: |
        python ninja_setup.py ${ninja_version} --prefix ${HOME}/.local/bin
        echo "::add-path::${HOME}/.local/bin"

    - name: CMake configure
      run: |
        cmake --version
        cmake -B build
      env:
        FC: gfortran-9

    - name: CMake build
      run: cmake --build build --parallel

    - name: CTest
      run: ctest --output-on-failure
      working-directory: build

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install .[tests]
    - run: pytest

    - name: Install Ninja
      run: |
        python ninja_setup.py ${ninja_version} --prefix ${HOME}/.local/bin
        echo "::add-path::${HOME}/.local/bin"

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --output-on-failure
      working-directory: build

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - run: pip install .[tests]
    - run: pytest

    - name: Install Ninja
      run: |
        python ninja_setup.py ${ninja_version} --prefix ${HOME}/.local/bin
        echo "::add-path::${HOME}/.local/bin"

    - run: cmake -B build

    - run: cmake --build build --parallel

    - run: ctest --output-on-failure
      working-directory: build
