name: ci_linux
env:
  cmake_version: '3.18.1'
  CMAKE_GENERATOR: Ninja
  FC: gfortran-9
  CC: gcc-9

on:
  push:
    paths:
      - "**.cmake"
      - "**.py"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_linux.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy .
    - run: pytest

    - name: Install CMake
      run: |
        cmake_setup ${cmake_version} --prefix ${HOME}/.local
        echo "::add-path::${HOME}/.local/cmake-${cmake_version}-Linux-x86_64/bin"

    - name: Install Ninja
      run: |
        ninja_setup --prefix ${HOME}/.local/bin
        echo "::add-path::${HOME}/.local/bin"

    - name: CMake configure
      run: |
        cmake --version
        cmake -B build

    - name: CMake build
      run: cmake --build build --parallel

    - name: CTest
      run: ctest --output-on-failure
      working-directory: build
