name: ci_mac
env:
  CMAKE_GENERATOR: Ninja
  FC: gfortran-9
  CC: gcc-9

on:
  push:
    paths:
      - "**.cmake"
      - "**.py"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_mac.yml"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install .[tests]
    - run: pytest

    - name: Install Ninja
      run: |
        ninja_setup --prefix ${HOME}/.local/bin
        echo "::add-path::${HOME}/.local/bin"

    - run: cmake -B build

    - run: cmake --build build --parallel

    - run: ctest --output-on-failure
      working-directory: build
